
import { PortfolioData } from './types';

export const portfolioData: PortfolioData = {
  "hunter": {
    "name": "Senior Dev",
    "title": "Full Stack Engineer",
    "hr": 999,
    "mr": 999,
    "unity": 30751,
    "quote": "A hunter must adapt. Always learning, always optimizing.",
    "equipment": [
      { "slot": "Weapon", "name": "React.js \"Fiber\"", "iconType": "sword", "color": "#61dafb" },
      { "slot": "Helm", "name": "Next.js Helm X", "iconType": "helm", "color": "#ffffff" },
      { "slot": "Mail", "name": "Tailwind Mail α", "iconType": "mail", "color": "#38bdf8" },
      { "slot": "Arms", "name": "TypeScript Vambraces", "iconType": "arms", "color": "#3178c6" },
      { "slot": "Coil", "name": "Node.js Coil β", "iconType": "coil", "color": "#68a063" },
      { "slot": "Legs", "name": "Postgres Greaves", "iconType": "legs", "color": "#336791" },
      { "slot": "Charm", "name": "Exploiter Charm III", "iconType": "charm", "color": "#a855f7" },
      { "slot": "Tool", "name": "VS Code Mantle", "iconType": "tool", "color": "#007acc" }
    ],
    "questStats": {
      "lowRank": 94,
      "highRank": 164,
      "masterRank": 278,
      "investigations": 64,
      "arena": 47,
      "guidingLands": 63
    }
  },
  "skills": [
    { "name": "React", "level": 7, "maxLevel": 7, "type": "FRONTEND", "description": "Increases rendering speed and component reusability." },
    { "name": "TypeScript", "level": 7, "maxLevel": 7, "type": "FRONTEND", "description": "Prevents runtime errors and improves code intelligence." },
    { "name": "Tailwind CSS", "level": 6, "maxLevel": 7, "type": "FRONTEND", "description": "Rapidly deploys style configurations." },
    { "name": "Next.js", "level": 6, "maxLevel": 7, "type": "FRONTEND", "description": "Grants server-side rendering capabilities." },
    { "name": "Node.js", "level": 5, "maxLevel": 7, "type": "BACKEND", "description": "Allows JavaScript execution outside the browser environment." },
    { "name": "PostgreSQL", "level": 5, "maxLevel": 7, "type": "BACKEND", "description": "Enhances data retention and complex query handling." },
    { "name": "AWS", "level": 4, "maxLevel": 7, "type": "TOOLS", "description": "Cloud infrastructure deployment mastery." },
    { "name": "Docker", "level": 4, "maxLevel": 7, "type": "TOOLS", "description": "Containerization for consistent environments." }
  ],
  "quests": [
    {
      "id": "job-1",
      "title": "Return of the Crazy One",
      "client": "Tech Corp Inc.",
      "difficulty": 5,
      "description": "Lead the frontend migration from legacy monolithic architecture to micro-frontends using React and Module Federation. Mentored junior hunters.",
      "rewards": ["Leadership", "Architecture", "Micro-frontends"],
      "completed": true,
      "tags": ["React", "TypeScript", "Webpack"],
      "type": "ASSIGNED",
      "location": "Tech Corp Inc.",
      "duration": "2 Years",
      "targetMonsters": ["Legacy Code", "Tech Debt"],
      "questTypeLabel": "Master Rank Assignment",
      "role": "Senior Frontend Engineer",
      "challenges": ["Zero downtime migration", "Cross-team coordination"],
      "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "job-2",
      "title": "Big Burly Bash",
      "client": "StartUp Studio",
      "difficulty": 4,
      "description": "Developed and maintained multiple client MVPs. Rapid prototyping and deployment to AWS infrastructure.",
      "rewards": ["Agile Development", "Full Stack", "AWS"],
      "completed": true,
      "tags": ["Node.js", "PostgreSQL", "Docker"],
      "type": "ASSIGNED",
      "location": "StartUp Studio",
      "duration": "18 Months",
      "targetMonsters": ["Bugs", "Deadlines"],
      "questTypeLabel": "Hunting Quest",
      "role": "Full Stack Developer",
      "challenges": ["Ambiguous requirements", "Rapid scaling"],
      "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "proj-1",
      "title": "E-Commerce Platform",
      "client": "Major Retailer",
      "difficulty": 5,
      "description": "Refactor the legacy checkout flow to reduce cart abandonment. Requires high-performance rendering and complex state management.",
      "rewards": ["React Mastery", "Conversion Rate +15%"],
      "completed": true,
      "tags": ["React", "Redux", "Node.js"],
      "type": "OPTIONAL",
      "duration": "3 Months",
      "targetMonsters": ["Cart Abandonment"],
      "questTypeLabel": "Slaying Quest",
      "role": "Lead Developer",
      "challenges": ["State management complexity", "Performance optimization"],
      "image": "https://images.unsplash.com/photo-1556742049-0cfed4f7a07d?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "proj-2",
      "title": "Real-time Analytics",
      "client": "FinTech Startup",
      "difficulty": 4,
      "description": "Construct a live data visualization board for stock tracking. Must handle WebSocket streams with zero latency.",
      "rewards": ["D3.js Visualization", "WebSocket Handling"],
      "completed": true,
      "tags": ["TypeScript", "D3.js", "Socket.io"],
      "type": "OPTIONAL",
      "duration": "6 Weeks",
      "targetMonsters": ["Latency"],
      "questTypeLabel": "Capture Quest",
      "role": "Frontend Developer",
      "challenges": ["Data throughput", "Visual clarity"],
      "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "proj-3",
      "title": "AI Chat Interface",
      "client": "Healthcare Provider",
      "difficulty": 4,
      "description": "Integrate LLM API for patient triage assistance. Ensure strict HIPAA compliance and accessible UI.",
      "rewards": ["Gemini API", "Accessibility"],
      "completed": false,
      "tags": ["Next.js", "AI Integration", "Tailwind"],
      "type": "OPTIONAL",
      "duration": "Ongoing",
      "targetMonsters": ["Compliance", "UX"],
      "questTypeLabel": "Research Quest",
      "role": "Solo Developer",
      "challenges": ["Model hallucination", "Accessibility standards"],
      "image": "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "proj-4",
      "title": "Portfolio \"World\"",
      "client": "Self-Directed",
      "difficulty": 3,
      "description": "Develop a highly interactive, themed portfolio website using React and Canvas API.",
      "rewards": ["Creativity", "Canvas API"],
      "completed": true,
      "tags": ["React", "Canvas", "Tailwind"],
      "type": "OPTIONAL",
      "duration": "2 Weeks",
      "targetMonsters": ["Boredom"],
      "questTypeLabel": "Event Quest",
      "role": "Designer & Developer",
      "challenges": ["Animation performance", "Theming consistency"],
      "image": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop",
      "images": [
        "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=600&auto=format&fit=crop"
      ],
      "githubUrl": "https://github.com/nickborrello/nickborrello.github.io",
      "liveUrl": "https://nickborrello.github.io"
    },
    {
      "id": "edu-1",
      "title": "B.S. Computer Science",
      "client": "University of Technology",
      "difficulty": 5,
      "description": "Four year campaign to master the fundamentals of computing, algorithms, and software engineering.",
      "rewards": ["Degree", "Algorithms", "Networking"],
      "completed": true,
      "tags": ["CS Fundamentals", "Java", "C++"],
      "type": "SPECIAL",
      "location": "University of Tech",
      "duration": "4 Years",
      "targetMonsters": ["Final Exams"],
      "questTypeLabel": "Special Assignment",
      "role": "Student",
      "challenges": ["Advanced Calculus", "Operating Systems"],
      "image": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "cert-1",
      "title": "AWS Certified Arch.",
      "client": "Amazon Web Services",
      "difficulty": 4,
      "description": "Validation of ability to design distributed systems on AWS.",
      "rewards": ["Certification", "Cloud Architecture"],
      "completed": true,
      "tags": ["AWS", "Cloud"],
      "type": "SPECIAL",
      "duration": "Self-Paced",
      "targetMonsters": ["Exam"],
      "questTypeLabel": "Optional Quest",
      "role": "Examinee",
      "challenges": ["System Design", "Security Best Practices"],
      "image": "https://images.unsplash.com/photo-1523289333742-be1143f6b766?q=80&w=600&auto=format&fit=crop"
    }
  ]
};
