
import { PortfolioData } from './types';

export const portfolioData: PortfolioData = {
  "hunter": {
    "name": "Senior Dev",
    "title": "Full Stack Engineer",
    "hr": 999,
    "mr": 999,
    "unity": 30751,
    "quote": "A hunter must adapt. Always learning, always optimizing.",
    "equipment": [
      { "slot": "Weapon", "name": "React.js \"Fiber\"", "iconType": "sword", "color": "#61dafb" },
      { "slot": "Helm", "name": "Next.js Helm X", "iconType": "helm", "color": "#ffffff" },
      { "slot": "Mail", "name": "Tailwind Mail α", "iconType": "mail", "color": "#38bdf8" },
      { "slot": "Arms", "name": "TypeScript Vambraces", "iconType": "arms", "color": "#3178c6" },
      { "slot": "Coil", "name": "Node.js Coil β", "iconType": "coil", "color": "#68a063" },
      { "slot": "Legs", "name": "Postgres Greaves", "iconType": "legs", "color": "#336791" },
      { "slot": "Charm", "name": "Exploiter Charm III", "iconType": "charm", "color": "#a855f7" },
      { "slot": "Tool", "name": "VS Code Mantle", "iconType": "tool", "color": "#007acc" }
    ],
    "questStats": {
      "lowRank": 94,
      "highRank": 164,
      "masterRank": 278,
      "investigations": 64,
      "arena": 47,
      "guidingLands": 63
    }
  },
  "skills": [
    { "name": "React", "level": 7, "maxLevel": 7, "type": "FRONTEND", "description": "Increases rendering speed and component reusability." },
    { "name": "TypeScript", "level": 7, "maxLevel": 7, "type": "FRONTEND", "description": "Prevents runtime errors and improves code intelligence." },
    { "name": "Tailwind CSS", "level": 6, "maxLevel": 7, "type": "FRONTEND", "description": "Rapidly deploys style configurations." },
    { "name": "Next.js", "level": 6, "maxLevel": 7, "type": "FRONTEND", "description": "Grants server-side rendering capabilities." },
    { "name": "Node.js", "level": 5, "maxLevel": 7, "type": "BACKEND", "description": "Allows JavaScript execution outside the browser environment." },
    { "name": "PostgreSQL", "level": 5, "maxLevel": 7, "type": "BACKEND", "description": "Enhances data retention and complex query handling." },
    { "name": "AWS", "level": 4, "maxLevel": 7, "type": "TOOLS", "description": "Cloud infrastructure deployment mastery." },
    { "name": "Docker", "level": 4, "maxLevel": 7, "type": "TOOLS", "description": "Containerization for consistent environments." }
  ],
  "quests": [
    {
      "id": "job-1",
      "title": "Hospital Kiosk Software Application",
      "client": "CS-3733-D23-Team-E",
      "difficulty": 5,
      "description": "Led frontend team for a JavaFX application, coordinating with hospital staff to meet stakeholder needs.",
      "rewards": ["Leadership", "JavaFX", "Team Coordination"],
      "completed": true,
      "tags": ["Java", "JavaFX", "Frontend"],
      "type": "ASSIGNED",
      "location": "Hospital",
      "duration": "Academic Project",
      "targetMonsters": ["Legacy Systems", "User Requirements"],
      "questTypeLabel": "Master Rank Assignment",
      "role": "Frontend Team Lead",
      "challenges": ["Stakeholder coordination", "UI/UX design"],
      "image": "/kiosk.png",
      "githubUrl": "https://github.com/CS-3733-D23-Team-E?view_as=public"
    },
    {
      "id": "job-2",
      "title": "Staffing Tool Application Security",
      "client": "Internal Project",
      "difficulty": 4,
      "description": "Enhanced API security by configuring Auth0 roles and permissions within a full-stack web app.",
      "rewards": ["Security", "Auth0", "Full Stack"],
      "completed": true,
      "tags": ["Tailwind", "TypeScript", "React", "Auth0"],
      "type": "ASSIGNED",
      "location": "Corporate",
      "duration": "Development Project",
      "targetMonsters": ["Security Vulnerabilities", "Access Control"],
      "questTypeLabel": "Hunting Quest",
      "role": "Security Engineer",
      "challenges": ["Role configuration", "API protection"],
      "image": "/staffing_tool.png"
    },
    {
      "id": "proj-1",
      "title": "PDF Keyword Search Tool",
      "client": "Productivity Tool",
      "difficulty": 4,
      "description": "Built a Python+Qt desktop tool to extract key insights from large document sets instantly.",
      "rewards": ["Python", "Qt", "Document Processing"],
      "completed": true,
      "tags": ["Python", "Qt", "Desktop App"],
      "type": "OPTIONAL",
      "duration": "Development Project",
      "targetMonsters": ["Manual Document Review"],
      "questTypeLabel": "Slaying Quest",
      "role": "Solo Developer",
      "challenges": ["PDF parsing", "GUI design"],
      "image": "/search_tool.png"
    },
    {
      "id": "proj-2",
      "title": "Syllablast Puzzle Game",
      "client": "Personal Project",
      "difficulty": 3,
      "description": "Next.js puzzle game where players reconstruct words by swapping syllables on a 4×4 grid.",
      "rewards": ["Game Development", "Next.js", "Puzzle Logic"],
      "completed": true,
      "tags": ["Next.js", "TypeScript", "React", "Tailwind"],
      "type": "OPTIONAL",
      "duration": "2 Weeks",
      "targetMonsters": ["Word Reconstruction"],
      "questTypeLabel": "Capture Quest",
      "role": "Game Developer",
      "challenges": ["Game mechanics", "Word database"],
      "image": "/syllablast.png",
      "liveUrl": "https://nickborrello.github.io/syllablast/"
    },
    {
      "id": "exp-1",
      "title": "Process Engineering Intern",
      "client": "Allegro Microsystems",
      "difficulty": 4,
      "description": "Created Azure DevOps pipelines to automate test driver deployments and streamline CI/CD workflows.",
      "rewards": ["DevOps", "Automation", "Azure"],
      "completed": true,
      "tags": ["Azure DevOps", "CI/CD", "Automation"],
      "type": "ASSIGNED",
      "location": "Allegro Microsystems",
      "duration": "Internship",
      "targetMonsters": ["Manual Deployments", "Process Inefficiency"],
      "questTypeLabel": "Support Quest",
      "role": "Process Engineering Intern",
      "challenges": ["Pipeline design", "Deployment automation"],
      "image": "/exp1.svg"
    },
    {
      "id": "exp-2",
      "title": "Software Engineer – Baystate Pet & Garden",
      "client": "Baystate Pet & Garden",
      "difficulty": 5,
      "description": "Built a Python desktop app to automate product registration and integrate with web inventory systems.",
      "rewards": ["Python", "Desktop Apps", "Inventory Integration"],
      "completed": true,
      "tags": ["Python", "Desktop Development", "Inventory"],
      "type": "ASSIGNED",
      "location": "Baystate Pet & Garden",
      "duration": "Full-time",
      "targetMonsters": ["Manual Registration", "Inventory Sync"],
      "questTypeLabel": "Hunting Quest",
      "role": "Software Engineer",
      "challenges": ["System integration", "User adoption"],
      "image": "/exp2.svg"
    },
    {
      "id": "proj-3",
      "title": "AI Chat Interface",
      "client": "Healthcare Provider",
      "difficulty": 4,
      "description": "Integrate LLM API for patient triage assistance. Ensure strict HIPAA compliance and accessible UI.",
      "rewards": ["Gemini API", "Accessibility"],
      "completed": false,
      "tags": ["Next.js", "AI Integration", "Tailwind"],
      "type": "OPTIONAL",
      "duration": "Ongoing",
      "targetMonsters": ["Compliance", "UX"],
      "questTypeLabel": "Research Quest",
      "role": "Solo Developer",
      "challenges": ["Model hallucination", "Accessibility standards"],
      "image": "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "proj-4",
      "title": "Portfolio \"World\"",
      "client": "Self-Directed",
      "difficulty": 3,
      "description": "Develop a highly interactive, themed portfolio website using React and Canvas API.",
      "rewards": ["Creativity", "Canvas API"],
      "completed": true,
      "tags": ["React", "Canvas", "Tailwind"],
      "type": "OPTIONAL",
      "duration": "2 Weeks",
      "targetMonsters": ["Boredom"],
      "questTypeLabel": "Event Quest",
      "role": "Designer & Developer",
      "challenges": ["Animation performance", "Theming consistency"],
      "image": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop",
      "images": [
        "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=600&auto=format&fit=crop"
      ],
      "githubUrl": "https://github.com/nickborrello/nickborrello.github.io",
      "liveUrl": "https://nickborrello.github.io"
    },
    {
      "id": "edu-1",
      "title": "B.S. Computer Science",
      "client": "University of Technology",
      "difficulty": 5,
      "description": "Four year campaign to master the fundamentals of computing, algorithms, and software engineering.",
      "rewards": ["Degree", "Algorithms", "Networking"],
      "completed": true,
      "tags": ["CS Fundamentals", "Java", "C++"],
      "type": "SPECIAL",
      "location": "University of Tech",
      "duration": "4 Years",
      "targetMonsters": ["Final Exams"],
      "questTypeLabel": "Special Assignment",
      "role": "Student",
      "challenges": ["Advanced Calculus", "Operating Systems"],
      "image": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop"
    },
    {
      "id": "cert-1",
      "title": "AWS Certified Arch.",
      "client": "Amazon Web Services",
      "difficulty": 4,
      "description": "Validation of ability to design distributed systems on AWS.",
      "rewards": ["Certification", "Cloud Architecture"],
      "completed": true,
      "tags": ["AWS", "Cloud"],
      "type": "SPECIAL",
      "duration": "Self-Paced",
      "targetMonsters": ["Exam"],
      "questTypeLabel": "Optional Quest",
      "role": "Examinee",
      "challenges": ["System Design", "Security Best Practices"],
      "image": "https://images.unsplash.com/photo-1523289333742-be1143f6b766?q=80&w=600&auto=format&fit=crop"
    }
  ]
};
